"""add frequency_cap to campaigns and conversions table

Revision ID: 1bc890180a5c
Revises: 1c32b33a1f06
Create Date: 2026-04-14 13:30:33.750753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1bc890180a5c'
down_revision: Union[str, Sequence[str], None] = '1c32b33a1f06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('impression_id', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('event_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['impression_id'], ['impressions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('campaigns', sa.Column('frequency_cap', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('campaigns', 'frequency_cap')
    op.drop_table('conversions')
    # ### end Alembic commands ###
