"""add images_status to campaigns

Revision ID: 1c32b33a1f06
Revises: 748fc47353b0
Create Date: 2026-04-11 13:31:52.751683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c32b33a1f06'
down_revision: Union[str, Sequence[str], None] = '748fc47353b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaigns', sa.Column('images_status', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('campaigns', 'images_status')
    # ### end Alembic commands ###
