"""add impressions table

Revision ID: 748fc47353b0
Revises: f1897c6c4535
Create Date: 2026-04-11 12:50:11.000717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '748fc47353b0'
down_revision: Union[str, Sequence[str], None] = 'f1897c6c4535'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('impressions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('zone_id', sa.String(), nullable=False),
    sa.Column('campaign_id', sa.String(), nullable=False),
    sa.Column('cpm_paid', sa.Float(), nullable=False),
    sa.Column('page_url', sa.Text(), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('clicked', sa.Boolean(), nullable=False),
    sa.Column('clicked_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['zone_id'], ['inventory_zones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('impressions')
    # ### end Alembic commands ###
