"""initial schema

Revision ID: f1897c6c4535
Revises: 
Create Date: 2026-04-11 11:40:57.556296

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1897c6c4535'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('advertisers',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('website', sa.Text(), nullable=True),
    sa.Column('balance_usd', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('publishers',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('site_url', sa.Text(), nullable=True),
    sa.Column('instagram_handle', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('campaigns',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('advertiser_id', sa.String(), nullable=False),
    sa.Column('product_url', sa.Text(), nullable=False),
    sa.Column('brand_name', sa.String(length=255), nullable=True),
    sa.Column('brand_description', sa.Text(), nullable=True),
    sa.Column('value_propositions', sa.JSON(), nullable=True),
    sa.Column('target_audience', sa.JSON(), nullable=True),
    sa.Column('tone_of_voice', sa.Text(), nullable=True),
    sa.Column('ad_creatives', sa.JSON(), nullable=True),
    sa.Column('suggested_categories', sa.JSON(), nullable=True),
    sa.Column('bid_floor_cpm', sa.Float(), nullable=True),
    sa.Column('daily_budget_usd', sa.Float(), nullable=True),
    sa.Column('total_budget_usd', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'ACTIVE', 'PAUSED', 'COMPLETED', 'FAILED', name='campaignstatus'), nullable=False),
    sa.Column('is_listed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['advertiser_id'], ['advertisers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inventory_zones',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('publisher_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('zone_type', sa.String(length=50), nullable=False),
    sa.Column('dimensions', sa.String(length=50), nullable=True),
    sa.Column('recommended_cpm_usd', sa.Float(), nullable=True),
    sa.Column('placement_rationale', sa.Text(), nullable=True),
    sa.Column('categories', sa.JSON(), nullable=True),
    sa.Column('serve_tag', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['publisher_id'], ['publishers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inventory_zones')
    op.drop_table('campaigns')
    op.drop_table('publishers')
    op.drop_table('advertisers')
    # ### end Alembic commands ###
